name: Upload to Borealis
on:
  release:
    types: [created]
  workflow_dispatch:  # Allows manual triggering from Actions tab

jobs:
  upload-to-borealis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Send repo to Borealis
        uses: IQSS/dataverse-uploader@v1.6
        with:
          DATAVERSE_TOKEN: ${{secrets.DATAVERSE_TOKEN}}
          DATAVERSE_SERVER: https://borealisdata.ca
          DATAVERSE_DATASET_DOI: doi:10.5683/SP3/FCMJYR
          DELETE: False
          PUBLISH: False
